apiVersion: v2
name: generic-helm-chart
description: A Generic Helm Chart to support easy deployment of micro-services
icon: "https://helm.sh/img/helm.svg"
type: application
version: "0.3.8"
appVersion: "0.0.1"
keywords:
- generic-helm-chart
- micro-service
maintainers:
- name: mkcc6  # marcus cheng
  url: https://github.com/mkcc6
  email: marcus.cheng@hextrust.com
- name: ryanth2022  # Ryan (Phuc Truong)
  url: https://github.com/ryanth2022
  email: phuc.truong@hextrust.com
- name: AaronForce1  # Aaron Baideme
  url: https://github.com/aaronforce1
  email: avbaideme@proton.me
